server:
  port: 10100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/spzx-cloud-user?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    
    nacos:
      config:
        server-addr: 47.121.222.152:8848
      discovery:
        server-addr: 47.121.222.152:8848
        cluster-name: SH



  config:
    import:
      - nacos:zack-cloud-user-dev.yml
      - nacos:zack-cloud-user.yml

  application:
      name: zack-cloud-user

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zack.cloud.user.entity
  mapper-locations: classpath:/mapper/*.xml
