server:
  10100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: dbc:mysql://localhost:3308/spzx-cloud-user?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
      nacos:
        discovery:
          server-addr: 47.121.222.152:8848
  application:
      name: zack-cloud-user

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zack.cloud.user.entity
  mapper-locations: classpath:/mapper/*.xml