# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.142:3308/spzx-cloud-order?characterEncoding=UTF8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 47.121.222.152:8848
  application:
    name: zack-cloud-order

# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zack.cloud.order.entity
  mapper-locations: classpath:/mapper/*.xml
