# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/spzx-cloud-order?characterEncoding=UTF8
    username: root
    password: root
  cloud:
    openfeign:
      client:
        config:
          default:
           loggerLevel: full
           read-timeout: 2000
           connect-timeout: 2000
           retryer: com.zack.cloud.feign.retryer.FeignClientRetryer
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 47.121.222.152:8848
        cluster-name: SH
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: 47.121.222.152:8848
            dataId: sentinel-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  application:
    name: zack-cloud-order

# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zack.cloud.order.entity
  mapper-locations: classpath:/mapper/*.xml
feign:
  sentinel:
    enabled: true